//JavaScript Number Methods Tutorial
//toString Method
let Message1 ="The examples below use the toString() method";
console.log(Message1);

let a = 13;
a = a.toString();
console.log(a); 
console.log(typeof a);

//toExponential Method
let Message2 ="\nThe examples below use the toExponential() method";
console.log(Message2);
let b = 9.787;
b = b.toExponential();
console.log(b);
console.log(typeof b)
