let a = 5;
let b = 6;
let c = a + b;
let d = b-a;
let e = a*b;
let f = e/a;
let g = 32%a;
let h = 10;
h++;
let j = 20;
j--;
let k = a**a;
document.getElementById("addition").innerHTML = c;
document.getElementById("subtraction").innerHTML = d;
document.getElementById("multiplication").innerHTML = e;
document.getElementById("division").innerHTML = f;
document.getElementById("modulus").innerHTML = g;
document.getElementById("incrementing").innerHTML = h;
document.getElementById("decrementing").innerHTML = j;
document.getElementById("exponentiation").innerHTML = k;